import { DEFAULT_ENTITY_TYPE_DEFINITIONS } from "@/lib/entities/entity-types";
import type { Settings } from "@/lib/types";

export const DEFAULT_SETTINGS: Settings = {
  theme: { mode: "dark", accent: "zinc", radius: "0.5rem" },
  entityTypes: DEFAULT_ENTITY_TYPE_DEFINITIONS,
  confidenceTypes: [
    { id: "inferred", label: "Inferred", color: "#94a3b8", order: 0 },
    { id: "deduced", label: "Deduced", color: "#60a5fa", order: 1 },
    { id: "unsure", label: "Unsure", color: "#fbbf24", order: 2 },
    { id: "sure", label: "Sure", color: "#34d399", order: 3 },
    {
      id: "debunked",
      label: "Debunked",
      color: "#f87171",
      order: 4,
      isTerminal: true,
    },
  ],
  fieldTypes: [
    { id: "shortText", label: "Short text", enabled: true, order: 0 },
    { id: "longText", label: "Long text", enabled: true, order: 1 },
    {
      id: "richMarkdown",
      label: "Markdown (GFM + Obsidian)",
      enabled: true,
      order: 2,
    },
    {
      id: "obsidianMarkdown",
      label: "Markdown (alias)",
      enabled: true,
      order: 3,
    },
    { id: "url", label: "URL", enabled: true, order: 4 },
    { id: "email", label: "Email", enabled: true, order: 5 },
    { id: "phone", label: "Phone", enabled: true, order: 6 },
    { id: "number", label: "Number", enabled: true, order: 7 },
    { id: "date", label: "Date", enabled: true, order: 8 },
    { id: "datetime", label: "Date & time", enabled: true, order: 9 },
    { id: "dateRange", label: "Date range", enabled: true, order: 10 },
    { id: "dates", label: "Multiple dates", enabled: true, order: 11 },
    { id: "location", label: "Location", enabled: true, order: 12 },
    { id: "boolean", label: "Yes / No", enabled: true, order: 13 },
    { id: "dropdown", label: "Dropdown", enabled: true, order: 14 },
    { id: "checklist", label: "Checklist", enabled: true, order: 15 },
    { id: "tags", label: "Tags", enabled: true, order: 16 },
    { id: "image", label: "Image", enabled: true, order: 17 },
    { id: "entityLink", label: "Link to entity", enabled: true, order: 18 },
  ],
  sectionTemplates: [],
  entityTemplates: [
    {
      id: "person-default",
      title: "Person",
      entityType: "person",
      sections: [
        { title: "Overview", order: 0, fields: [] },
        { title: "Contact", order: 1, fields: [] },
        { title: "Notes", order: 2, fields: [] },
      ],
    },
    {
      id: "org-default",
      title: "Organization",
      entityType: "organization",
      sections: [
        { title: "Overview", order: 0, fields: [] },
        { title: "Notes", order: 1, fields: [] },
      ],
    },
    {
      id: "domain-default",
      title: "Domain",
      entityType: "domain",
      sections: [
        { title: "WHOIS", order: 0, fields: [] },
        { title: "DNS", order: 1, fields: [] },
        { title: "Notes", order: 2, fields: [] },
      ],
    },
    {
      id: "general-default",
      title: "General",
      entityType: "general",
      sections: [
        { title: "Overview", order: 0, fields: [] },
        { title: "Notes", order: 1, fields: [] },
      ],
    },
    {
      id: "email-default",
      title: "Email",
      entityType: "email",
      sections: [
        { title: "Address", order: 0, fields: [] },
        { title: "Context", order: 1, fields: [] },
        { title: "Notes", order: 2, fields: [] },
      ],
    },
    {
      id: "phone-default",
      title: "Phone",
      entityType: "phone",
      sections: [
        { title: "Number", order: 0, fields: [] },
        { title: "Context", order: 1, fields: [] },
        { title: "Notes", order: 2, fields: [] },
      ],
    },
  ],
  relationshipTypes: [
    {
      id: "associated_with",
      label: "Associated with",
      inverseLabel: "Associated with",
      fromTypes: ["person", "organization", "domain", "general"],
      toTypes: ["person", "organization", "domain", "general"],
    },
    {
      id: "employed_by",
      label: "Employed by",
      inverseLabel: "Employs",
      fromTypes: ["person"],
      toTypes: ["organization"],
    },
    {
      id: "owns",
      label: "Owns",
      inverseLabel: "Owned by",
      fromTypes: ["person", "organization"],
      toTypes: ["domain", "general"],
    },
    {
      id: "registered_to",
      label: "Registered to",
      inverseLabel: "Registration for",
      fromTypes: ["domain"],
      toTypes: ["organization", "person"],
    },
    {
      id: "parent_of",
      label: "Parent of",
      inverseLabel: "Child of",
      fromTypes: ["person"],
      toTypes: ["person"],
    },
    {
      id: "child_of",
      label: "Child of",
      inverseLabel: "Parent of",
      fromTypes: ["person"],
      toTypes: ["person"],
    },
    {
      id: "sibling_of",
      label: "Sibling of",
      inverseLabel: "Sibling of",
      fromTypes: ["person"],
      toTypes: ["person"],
    },
    {
      id: "spouse_of",
      label: "Spouse of",
      inverseLabel: "Spouse of",
      fromTypes: ["person"],
      toTypes: ["person"],
    },
    {
      id: "cousin_of",
      label: "Cousin of",
      inverseLabel: "Cousin of",
      fromTypes: ["person"],
      toTypes: ["person"],
    },
    {
      id: "grandparent_of",
      label: "Grandparent of",
      inverseLabel: "Grandchild of",
      fromTypes: ["person"],
      toTypes: ["person"],
    },
    {
      id: "colleague_of",
      label: "Colleague of",
      inverseLabel: "Colleague of",
      fromTypes: ["person"],
      toTypes: ["person", "organization"],
    },
    {
      id: "boss_of",
      label: "Boss of",
      inverseLabel: "Reports to",
      fromTypes: ["person"],
      toTypes: ["person", "organization"],
    },
    {
      id: "secretary_of",
      label: "Secretary of",
      inverseLabel: "Assisted by",
      fromTypes: ["person"],
      toTypes: ["person", "organization"],
    },
  ],
  eventTypes: ["observation", "contact", "legal", "digital", "other"],
  categories: { tools: [], resources: [] },
};

export { defaultProvenance } from "@/lib/proof/helpers";
